import { useMemo } from 'react'
import type { SimulationContextState } from '../SimulationContext'

/**
 * Custom hook to build the SimulationContext value object
 * Extracted from SimulationProvider to reduce complexity
 */
// eslint-disable-next-line max-lines-per-function -- Large component function
export function useSimulationContextValue(
  state: Record<string, unknown>,
  configManagement: {
    getCurrentConfiguration: () => unknown
    saveCurrentConfiguration: (name: string) => void
    loadSavedConfiguration: (config: unknown) => void
    resetToDefaults: () => void
  },
  performSimulation: () => void,
  setEndOfLifeRounded: (value: number) => void,
): SimulationContextState {
  const {
    rendite, setRendite,
    steuerlast, setSteuerlast,
    teilfreistellungsquote, setTeilfreistellungsquote,
    freibetragPerYear, setFreibetragPerYear,
    basiszinsConfiguration, setBasiszinsConfiguration,
    steuerReduzierenEndkapitalSparphase, setSteuerReduzierenEndkapitalSparphase,
    steuerReduzierenEndkapitalEntspharphase, setSteuerReduzierenEndkapitalEntspharphase,
    grundfreibetragAktiv, setGrundfreibetragAktiv,
    grundfreibetragBetrag, setGrundfreibetragBetrag,
    personalTaxRate, setPersonalTaxRate,
    guenstigerPruefungAktiv, setGuenstigerPruefungAktiv,
    kirchensteuerAktiv, setKirchensteuerAktiv,
    kirchensteuersatz, setKirchensteuersatz,
    returnMode, setReturnMode,
    averageReturn, setAverageReturn,
    standardDeviation, setStandardDeviation,
    randomSeed, setRandomSeed,
    variableReturns, setVariableReturns,
    historicalIndex, setHistoricalIndex,
    blackSwanReturns, setBlackSwanReturns,
    blackSwanEventName, setBlackSwanEventName,
    inflationScenarioRates, setInflationScenarioRates,
    inflationScenarioReturnModifiers, setInflationScenarioReturnModifiers,
    inflationScenarioName, setInflationScenarioName,
    multiAssetConfig, setMultiAssetConfig,
    withdrawalMultiAssetConfig, setWithdrawalMultiAssetConfig,
    inflationAktivSparphase, setInflationAktivSparphase,
    inflationsrateSparphase, setInflationsrateSparphase,
    inflationAnwendungSparphase, setInflationAnwendungSparphase,
    startEnd, setStartEnd,
    sparplan, setSparplan,
    simulationAnnual, setSimulationAnnual,
    sparplanElemente, setSparplanElemente,
    endOfLife,
    lifeExpectancyTable, setLifeExpectancyTable,
    customLifeExpectancy, setCustomLifeExpectancy,
    planningMode, setPlanningMode,
    gender, setGender,
    spouse, setSpouse,
    birthYear, setBirthYear,
    expectedLifespan, setExpectedLifespan,
    useAutomaticCalculation, setUseAutomaticCalculation,
    simulationData,
    isLoading,
    withdrawalResults, setWithdrawalResults,
    withdrawalConfig, setWithdrawalConfig,
    statutoryPensionConfig, setStatutoryPensionConfig,
    coupleStatutoryPensionConfig, setCoupleStatutoryPensionConfig,
    careCostConfiguration, setCareCostConfiguration,
    financialGoals, setFinancialGoals,
  } = state

  const {
    getCurrentConfiguration,
    saveCurrentConfiguration,
    loadSavedConfiguration,
    resetToDefaults,
  } = configManagement

  // eslint-disable-next-line max-lines-per-function -- Large component render function
  return useMemo(() => ({
    rendite, setRendite,
    steuerlast, setSteuerlast,
    teilfreistellungsquote, setTeilfreistellungsquote,
    freibetragPerYear, setFreibetragPerYear,
    basiszinsConfiguration, setBasiszinsConfiguration,
    steuerReduzierenEndkapitalSparphase, setSteuerReduzierenEndkapitalSparphase,
    steuerReduzierenEndkapitalEntspharphase, setSteuerReduzierenEndkapitalEntspharphase,
    grundfreibetragAktiv, setGrundfreibetragAktiv,
    grundfreibetragBetrag, setGrundfreibetragBetrag,
    personalTaxRate, setPersonalTaxRate,
    guenstigerPruefungAktiv, setGuenstigerPruefungAktiv,
    kirchensteuerAktiv, setKirchensteuerAktiv,
    kirchensteuersatz, setKirchensteuersatz,
    returnMode, setReturnMode,
    averageReturn, setAverageReturn,
    standardDeviation, setStandardDeviation,
    randomSeed, setRandomSeed,
    variableReturns, setVariableReturns,
    historicalIndex, setHistoricalIndex,
    blackSwanReturns, setBlackSwanReturns,
    blackSwanEventName, setBlackSwanEventName,
    inflationScenarioRates, setInflationScenarioRates,
    inflationScenarioReturnModifiers, setInflationScenarioReturnModifiers,
    inflationScenarioName, setInflationScenarioName,
    multiAssetConfig, setMultiAssetConfig,
    withdrawalMultiAssetConfig, setWithdrawalMultiAssetConfig,
    inflationAktivSparphase, setInflationAktivSparphase,
    inflationsrateSparphase, setInflationsrateSparphase,
    inflationAnwendungSparphase, setInflationAnwendungSparphase,
    startEnd, setStartEnd,
    sparplan, setSparplan,
    simulationAnnual, setSimulationAnnual,
    sparplanElemente, setSparplanElemente,
    endOfLife, setEndOfLife: setEndOfLifeRounded,
    lifeExpectancyTable, setLifeExpectancyTable,
    customLifeExpectancy, setCustomLifeExpectancy,
    planningMode, setPlanningMode,
    gender, setGender,
    spouse, setSpouse,
    birthYear, setBirthYear,
    expectedLifespan, setExpectedLifespan,
    useAutomaticCalculation, setUseAutomaticCalculation,
    simulationData,
    isLoading,
    withdrawalResults, setWithdrawalResults,
    performSimulation,
    getCurrentConfiguration,
    saveCurrentConfiguration,
    loadSavedConfiguration,
    resetToDefaults,
    withdrawalConfig, setWithdrawalConfig,
    statutoryPensionConfig, setStatutoryPensionConfig,
    coupleStatutoryPensionConfig, setCoupleStatutoryPensionConfig,
    careCostConfiguration, setCareCostConfiguration,
    financialGoals, setFinancialGoals,
    // eslint-disable-next-line react-hooks/exhaustive-deps -- Setter functions are stable
  }) as SimulationContextState, [
    rendite, steuerlast, teilfreistellungsquote, freibetragPerYear, basiszinsConfiguration,
    steuerReduzierenEndkapitalSparphase, steuerReduzierenEndkapitalEntspharphase,
    grundfreibetragAktiv, grundfreibetragBetrag,
    personalTaxRate, guenstigerPruefungAktiv,
    kirchensteuerAktiv, kirchensteuersatz,
    returnMode, averageReturn, standardDeviation, randomSeed, variableReturns, historicalIndex,
    blackSwanReturns, blackSwanEventName,
    inflationScenarioRates, inflationScenarioReturnModifiers, inflationScenarioName,
    multiAssetConfig, withdrawalMultiAssetConfig,
    inflationAktivSparphase, inflationsrateSparphase, inflationAnwendungSparphase,
    startEnd, sparplan, simulationAnnual, sparplanElemente,
    endOfLife, lifeExpectancyTable, customLifeExpectancy, planningMode, gender, spouse,
    birthYear, expectedLifespan, useAutomaticCalculation,
    simulationData, isLoading, withdrawalResults, performSimulation,
    getCurrentConfiguration, saveCurrentConfiguration, loadSavedConfiguration, resetToDefaults,
    withdrawalConfig, statutoryPensionConfig, coupleStatutoryPensionConfig, careCostConfiguration,
    financialGoals,
    setEndOfLifeRounded,
  ])
}
