/**
 * Excel Export Utility
 *
 * Generates Excel files with formulas for financial calculations.
 *
 * SECURITY NOTE: Uses xlsx@0.18.5 which has known vulnerabilities (ReDoS, Prototype Pollution).
 * These vulnerabilities require malicious input. Since this is a client-side only application
 * where users control their own data and we only export application-generated data (not parse
 * external files), the risk is minimal. All data is generated by the simulation and under user control.
 *
 * For future improvements, consider upgrading to xlsx from https://cdn.sheetjs.com when available in npm.
 */

import * as XLSX from 'xlsx'
import type { SimulationContextState } from '../contexts/SimulationContext'
import type { SavingsData } from './data-export'

/**
 * Format a number as German currency string for display in Excel
 */
function formatGermanCurrency(value: number): string {
  return new Intl.NumberFormat('de-DE', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(value)
}

/**
 * Format a number as German percentage string for display in Excel
 */
function formatGermanPercentage(value: number): string {
  return new Intl.NumberFormat('de-DE', {
    style: 'percent',
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(value / 100)
}

/**
 * Generate summary sheet data
 */
function generateSummarySheetData(context: SimulationContextState): string[][] {
  return [
    ['Zinseszins-Simulation - Sparphase', ''],
    ['', ''],
    ['Zeitraum', `${context.startEnd[0]} - ${context.startEnd[1]}`],
    ['Rendite p.a.', formatGermanPercentage(context.rendite)],
    ['Kapitalertragsteuer', formatGermanPercentage(context.steuerlast)],
    ['Teilfreistellungsquote', formatGermanPercentage(context.teilfreistellungsquote)],
    ['Freibetrag (Standard)', `${formatGermanCurrency(Object.values(context.freibetragPerYear)[0] || 0)} €`],
    ['', ''],
    ['Berechnungsmodus', context.simulationAnnual === 'yearly' ? 'Jährlich' : 'Monatlich'],
  ]
}

/**
 * Generate sparplan sheet data rows
 */
function generateSparplanRows(elements: SavingsData['sparplanElements']): unknown[][] {
  return elements.map(element => {
    const startDate = new Date(element.start)
    const startYear = startDate.getFullYear()
    const endCapital = 'gesamtkapitalNachSteuern' in element ? element.gesamtkapitalNachSteuern : 0

    return [
      element.type === 'sparplan' ? 'Sparplan' : 'Einmalzahlung',
      element.einzahlung,
      startYear,
      endCapital,
    ]
  })
}

/**
 * Apply German currency format to worksheet columns
 */
function applyCurrencyFormat(sheet: XLSX.WorkSheet, columns: number[], startRow = 1): void {
  const range = XLSX.utils.decode_range(sheet['!ref'] || 'A1')
  for (let R = startRow; R <= range.e.r; R++) {
    for (const col of columns) {
      const cellAddress = XLSX.utils.encode_cell({ r: R, c: col })
      if (sheet[cellAddress]) {
        sheet[cellAddress].z = '#,##0.00 "€"'
      }
    }
  }
}

/**
 * Generate Excel workbook with formulas for savings phase
 */
export function generateSavingsExcelWithFormulas(savingsData: SavingsData, context: SimulationContextState): XLSX.WorkBook {
  const wb = XLSX.utils.book_new()

  // Sheet 1: Summary
  const summaryData = generateSummarySheetData(context)
  const wsSummary = XLSX.utils.aoa_to_sheet(summaryData)
  XLSX.utils.book_append_sheet(wb, wsSummary, 'Übersicht')

  // Sheet 2: Sparplan Elements
  if (savingsData.sparplanElements?.length > 0) {
    const headers = ['Typ', 'Betrag (€)', 'Start', 'Kapital (nach Steuern)']
    const rows = generateSparplanRows(savingsData.sparplanElements)
    const wsSparplan = XLSX.utils.aoa_to_sheet([headers, ...rows])

    // Format currency columns B and D
    applyCurrencyFormat(wsSparplan, [1, 3])

    XLSX.utils.book_append_sheet(wb, wsSparplan, 'Sparpläne')
  }

  return wb
}

/**
 * Download Excel workbook as file
 */
export function downloadExcelFile(wb: XLSX.WorkBook, filename: string): void {
  XLSX.writeFile(wb, filename)
}

/**
 * Export savings data as Excel file with formulas
 */
export function exportSavingsDataToExcel(savingsData: SavingsData, context: SimulationContextState): void {
  try {
    const wb = generateSavingsExcelWithFormulas(savingsData, context)
    const filename = `Sparphase_${context.startEnd[0]}-${context.startEnd[1]}.xlsx`
    downloadExcelFile(wb, filename)
  } catch (error) {
    console.error('Excel export failed:', error)
    throw new Error('Excel-Export fehlgeschlagen')
  }
}

/**
 * Type for withdrawal data (avoiding 'any')
 */
interface WithdrawalDataForExcel {
  strategy?: string
  startingCapital?: number
  withdrawalFrequency?: 'yearly' | 'monthly'
  years?: Array<{
    year: number
    startingCapital?: number
    withdrawal?: number
    returns?: number
    tax?: number
    endingCapital?: number
  }>
}

/**
 * Get start and end years from withdrawal data
 */
function getWithdrawalYearRange(
  withdrawalData: WithdrawalDataForExcel,
  context: SimulationContextState,
): [number, number] {
  const startYear = withdrawalData.years?.[0]?.year || context.startEnd[1]
  const endYear = withdrawalData.years?.[withdrawalData.years.length - 1]?.year || context.endOfLife
  return [startYear, endYear]
}

/**
 * Generate withdrawal summary sheet data
 */
function generateWithdrawalSummaryData(
  withdrawalData: WithdrawalDataForExcel,
  context: SimulationContextState,
): string[][] {
  const [startYear, endYear] = getWithdrawalYearRange(withdrawalData, context)

  return [
    ['Zinseszins-Simulation - Entnahmephase', ''],
    ['', ''],
    ['Zeitraum', `${startYear} - ${endYear}`],
    ['Strategie', withdrawalData.strategy || 'Unbekannt'],
    ['Anfangskapital', `${formatGermanCurrency(withdrawalData.startingCapital || 0)} €`],
    ['Rendite p.a.', formatGermanPercentage(context.rendite)],
    ['Kapitalertragsteuer', formatGermanPercentage(context.steuerlast)],
    ['', ''],
    ['Entnahmefrequenz', withdrawalData.withdrawalFrequency === 'yearly' ? 'Jährlich' : 'Monatlich'],
  ]
}

/**
 * Generate withdrawal yearly data rows
 */
function generateWithdrawalYearlyRows(years: WithdrawalDataForExcel['years']): number[][] {
  if (!years) return []

  return years.map(row => [
    row.year,
    row.startingCapital || 0,
    row.withdrawal || 0,
    row.returns || 0,
    row.tax || 0,
    row.endingCapital || 0,
  ])
}

/**
 * Generate Excel workbook with formulas for withdrawal phase
 */
export function generateWithdrawalExcelWithFormulas(
  withdrawalData: WithdrawalDataForExcel,
  context: SimulationContextState,
): XLSX.WorkBook {
  const wb = XLSX.utils.book_new()

  // Sheet 1: Summary
  const summaryData = generateWithdrawalSummaryData(withdrawalData, context)
  const wsSummary = XLSX.utils.aoa_to_sheet(summaryData)
  XLSX.utils.book_append_sheet(wb, wsSummary, 'Übersicht')

  // Sheet 2: Yearly data
  if (withdrawalData.years?.length) {
    const headers = ['Jahr', 'Kapital Anfang', 'Entnahme', 'Rendite', 'Steuer', 'Kapital Ende']
    const dataRows = generateWithdrawalYearlyRows(withdrawalData.years)
    const wsData = XLSX.utils.aoa_to_sheet([headers, ...dataRows])

    // Format currency columns B through F
    applyCurrencyFormat(wsData, [1, 2, 3, 4, 5])

    XLSX.utils.book_append_sheet(wb, wsData, 'Jahres-Aufschlüsselung')
  }

  return wb
}

/**
 * Export withdrawal data as Excel file with formulas
 */
export function exportWithdrawalDataToExcel(withdrawalData: WithdrawalDataForExcel, context: SimulationContextState): void {
  try {
    const wb = generateWithdrawalExcelWithFormulas(withdrawalData, context)
    const [startYear, endYear] = getWithdrawalYearRange(withdrawalData, context)
    const filename = `Entnahmephase_${startYear}-${endYear}.xlsx`
    downloadExcelFile(wb, filename)
  } catch (error) {
    console.error('Excel export failed:', error)
    throw new Error('Excel-Export fehlgeschlagen')
  }
}

/**
 * Export complete simulation (savings + withdrawal) as Excel file
 */
export function exportCompleteDataToExcel(
  savingsData: SavingsData,
  withdrawalData: WithdrawalDataForExcel,
  context: SimulationContextState,
): void {
  try {
    const wb = XLSX.utils.book_new()

    // Add savings sheets
    const wbSavings = generateSavingsExcelWithFormulas(savingsData, context)
    wbSavings.SheetNames.forEach(sheetName => {
      const sheet = wbSavings.Sheets[sheetName]
      XLSX.utils.book_append_sheet(wb, sheet, `Sparphase_${sheetName}`)
    })

    // Add withdrawal sheets
    const wbWithdrawal = generateWithdrawalExcelWithFormulas(withdrawalData, context)
    wbWithdrawal.SheetNames.forEach(sheetName => {
      const sheet = wbWithdrawal.Sheets[sheetName]
      XLSX.utils.book_append_sheet(wb, sheet, `Entnahme_${sheetName}`)
    })

    const filename = `Komplett_${context.startEnd[0]}-${context.endOfLife}.xlsx`
    downloadExcelFile(wb, filename)
  } catch (error) {
    console.error('Excel export failed:', error)
    throw new Error('Excel-Export fehlgeschlagen')
  }
}
